In [2]:
import pandas as pd

In [3]:
file_path = '/Users/chojungseok/Desktop/mini_project/data/'
file_name = '세종도시교통공사_버스정류장_시설현황_20210924.csv'
bus_stop = pd.read_csv(file_path + file_name)

In [5]:
bus_stop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2482 entries, 0 to 2481
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연번      2482 non-null   int64
 1   노선번호    2482 non-null   object
 2   노선ID    2482 non-null   object
 3   정류소번호   2482 non-null   object
 4   정류소ID   2482 non-null   object
 5   정류소명    2482 non-null   object
 6   위도      2482 non-null   float64
 7   경도      2482 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 155.3+ KB

In [6]:
bus_stop.head()

,연번,노선번호,노선ID,정류소번호,정류소ID,정류소명,위도,경도
0,1,B0,SJB293000302,51121,SJB293064220,세종고속시외버스터미널(지하),36.470816,127.273172
1,2,B0,SJB293000302,51048,SJB293053011,한솔동,36.480340,127.262430
2,3,B0,SJB293000302,51007,SJB293053005,새롬동.나성동,36.486850,127.257850
3,4,B0,SJB293000302,51015,SJB293054003,다정동,36.493925,127.256398
4,5,B0,SJB293000302,52029,SJB293062006,정부세종청사남측,36.500887,127.259620

In [7]:
bus_stop.drop('연번', axis=1, inplace=True)
bus_stop

,노선번호,노선ID,정류소번호,정류소ID,정류소명,위도,경도
0,B0,SJB293000302,51121,SJB293064220,세종고속시외버스터미널(지하),36.470816,127.273172
1,B0,SJB293000302,51048,SJB293053011,한솔동,36.480340,127.262430
2,B0,SJB293000302,51007,SJB293053005,새롬동.나성동,36.486850,127.257850
3,B0,SJB293000302,51015,SJB293054003,다정동,36.493925,127.256398
4,B0,SJB293000302,52029,SJB293062006,정부세종청사남측,36.500887,127.259620
...,...,...,...,...,...,...,...
2477,691,SJB293000211,51050,SJB293058005,호탄리,36.476430,127.296450
2478,691,SJB293000211,51019,SJB293058004,신촌리,36.473750,127.288350
2479,691,SJB293000211,51020,SJB293058002,금남초등학교,36.471970,127.286290
2480,691,SJB293000211,34032,SJB293011030,용포리,36.468630,127.281350
2481,691,SJB293000211,51052,SJB293055058,세종고속시외버스터미널,36.468990,127.273588

In [10]:
bus_stop['노선번호'].dtype

dtype('O')